BEGIN
DECLARE @CHIEURONG FLOAT
DECLARE @CHIEUDAI FLOAT
DECLARE @CHUVI FLOAT
DECLARE @DIENTICH FLOAT
SET @CHUVI = 0
SET @DIENTICH = 0
SET @CHIEURONG = 10.0
SET @CHIEUDAI = 12.0
SELECT @CHUVI = (@CHIEURONG + @CHIEUDAI)*2 
SELECT @DIENTICH = @CHIEURONG*@CHIEUDAI 
PRINT ' CHU VI : ' + CAST(@CHUVI AS NVARCHAR )
PRINT ' DIEN TICH : ' + CAST(@DIENTICH AS NVARCHAR )
END
BEGIN
USE QLDA
SELECT * FROM NHANVIEN WHERE LUONG = ( SELECT MAX(LUONG) FROM NHANVIEN)
END
BEGIN
USE QLDA
DECLARE @PHONGNGHIENCUU TABLE ( 
HONV NVARCHAR(50),
TENLOT NVARCHAR(50),
TENNV NVARCHAR(50),
LUONG FLOAT)
INSERT INTO @PHONGNGHIENCUU (HONV, TENLOT, TENNV, LUONG)
SELECT HONV, TENLOT, TENNV, LUONG
FROM NHANVIEN
WHERE PHG = 5;
SELECT * FROM @PHONGNGHIENCUU
DECLARE @TB FLOAT
SET @TB = 0
SELECT @TB = AVG(LUONG) FROM @PHONGNGHIENCUU 
PRINT 'Trung Binh Luong: ' + CAST(@TB AS NVARCHAR)
SELECT * FROM @PHONGNGHIENCUU WHERE LUONG > @TB 
END
BEGIN
USE QLDA
SELECT * FROM NHANVIEN
SELECT * FROM PHONGBAN
DECLARE @TB1 FLOAT
DECLARE @TB2 FLOAT
SET @TB1= 0
SET @TB2= 0
SELECT @TB1 = AVG(LUONG) FROM NHANVIEN WHERE PHG = 4
PRINT 'Trung Binh Luong Phong 4: ' + CAST(@TB1 AS NVARCHAR)
SELECT @TB2 = AVG(LUONG) FROM NHANVIEN WHERE PHG = 5
PRINT 'Trung Binh Luong Phong 5: ' + CAST(@TB2 AS NVARCHAR)
SELECT 
    p.TENPHG AS [Tên Phòng Ban],
    COUNT(n.MANV) AS [Tổng nhân viên]
FROM PHONGBAN p
JOIN NHANVIEN n ON p.MAPHG = n.PHG
/*WHERE p.MAPHG = 4*/
GROUP BY p.TENPHG;
END
BEGIN
USE QLDA
SELECT * FROM PHONGBAN
SELECT * FROM DEAN
SELECT
    p.TENPHG AS [Tên Phòng Ban],
    COUNT(d.MADA) AS [Số Lượng Đề Án]
FROM PHONGBAN p
JOIN DEAN d ON p.MAPHG = d.PHONG
GROUP BY p.TENPHG;
END